name: Code Coverage

on: [pull_request]

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.12
      - name: Generate Report for reference branch
        run: |
          pwd
          pip install coverage coverage-lcov
          ls -lah
          PYTHONPATH=. coverage run -m unittest test/unittests.py
          PYTHONPATH=. coverage-lcov --output_file_path ref-lcov.info

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v3
        with:
          name: ref-lcov.info
          path: ref-lcov.info

  feat_branch_cov:
    runs-on: ubuntu-latest
    needs: base_branch_cov
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.12
      - name: Generate Report for feature branch
        run: |
          pwd
          pip install coverage coverage-lcov
          ls -lah
          PYTHONPATH=. coverage run -m unittest test/unittests.py
          PYTHONPATH=. coverage-lcov --output_file_path feat-lcov.info

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v3
        with:
          name: feat-lcov.info
          path: feat-lcov.info

  checks:
    runs-on: ubuntu-latest
    needs: feat_branch_cov
    steps:
    - name: Download code coverage report for base
      uses: actions/download-artifact@v3
      with:
        name: ref-lcov.info
    - name: Download code coverage report for feat
      uses: actions/download-artifact@v3
      with:
        name: feat-lcov.info
    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "feat-lcov.info"
        base-lcov-file: "ref-lcov.info"
        send-summary-comment: true
        show-annotations: "warning"
        minimum-ratio: 0 # Fails Github action once code coverage is decreasing

